spring:
  data:
    elasticsearch:
    ####集群名称，注意如果报错节点不存在，需要在$ES/config/elasticsearch.yml中配置：
    ###cluster.name: myEs

     cluster-name: myEs
    ####地址 
     cluster-nodes: 192.168.13.102:9300
  freemarker:
    # 设置模板后缀名
    suffix: .html
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**

